function Hd = decimfilter(Q,N)
%DECIMFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
%
% Generated on: 14-Jun-2012 11:43:14
%

Fpass = 900;   % Passband Frequency
Fstop = 1100;  % Stopband Frequency
Apass = 1;     % Passband Ripple (dB)
Astop = 60;    % Stopband Attenuation (dB)
Fs    = N;  % Sampling Frequency of input

h = fdesign.decimator(Q, 'Lowpass', 'fp,fst,ap,ast', Fpass, Fstop, ...
    Apass, Astop, Fs);

Hd = design(h, 'kaiserwin');



% [EOF]
