function Hd = filterBeforeDecim(varargin)
%FILTERBEFOREDECIM Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
%
% Generated on: 28-Jun-2012 12:50:31
%

Fpass = 1800;  % Passband Frequency
Fstop = 2000;  % Stopband Frequency
Apass = 1;     % Passband Ripple (dB)
Astop = 60;    % Stopband Attenuation (dB)
Fs    = 8000;  % Sampling Frequency
Q=1;
if nargin>0
    Fs=varargin{1};
    Fstop=.5*Fs;
    Fpass=.9*Fpass;
end
if nargin>1
    Fstop=varargin{2};
    Fpass=.9*varargin{2};
end
if nargin>2
    Q=varargin{3};
end
h = fdesign.decimator(Q, 'Lowpass', 'fp,fst,ap,ast', Fpass, Fstop, ...
    Apass, Astop, Fs);

Hd = design(h, 'kaiserwin');



% [EOF]
