function Hd = interfilter(P,N)
%INTERFILTER Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
%
% Generated on: 14-Jun-2012 11:42:41
%

Fpass = 900;   % Passband Frequency
Fstop = 1100;  % Stopband Frequency
Apass = 1;     % Passband Ripple (dB)
Astop = 60;    % Stopband Attenuation (dB)
Fs    = N;     % Sampling Frequency of output

h = fdesign.interpolator(P, 'Lowpass', 'fp,fst,ap,ast', Fpass, Fstop, ...
    Apass, Astop, Fs);

Hd = design(h, 'kaiserwin');



% [EOF]
