function Plot_Video_Parameters(parray,vid_nums,fs)
freqn=log2(fs);
for i=1:size(vid_nums)
    vid_num=vid_nums(i);
    fs=fs(i);
    if fs(end)==8
        %plot all the 8000 fps videos
        %will have id8,id8cut2, id8cut1, id8to4cut2, id8to4cut1, id8to2cut1
        figure('name',sprintf('%d%s',8000 ,'FPS Original Videos'))
        
        subplot(5,1,1);
        plot([parray(vid_num).freqN(freqn).rateN(3).cutN(3).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.Fo(:)],'.-');
        ylabel('Fo')
        legend('8000','8cut2','8cut1','8to4cut2','8to4cut1','8to2cut1')
        
        subplot(5,1,2);
        plot([parray(vid_num).freqN(freqn).rateN(3).cutN(3).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.OQ(:)],'.-');
        ylabel('OQ')
        
        subplot(5,1,3);
        plot([parray(vid_num).freqN(freqn).rateN(3).cutN(3).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.SI(:)],'.-');
        ylabel('SI')
        
        subplot(5,1,4);
        plot([parray(vid_num).freqN(freqn).rateN(3).cutN(3).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.RGG(:)],'.-');
        ylabel('RGG')
        
        subplot(5,1,5);
        plot([parray(vid_num).freqN(freqn).rateN(3).cutN(3).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.HNR(:)],'.-');
        ylabel('HNR')
        
        %         fs(end)=[];
        
        
    elseif ~isempty(fs) && fs(end)==4
        %plot all the 4000 fps videos
        %will have id4,id4cut1, id4to2cut1 4to8cut2 4to8cut1
        figure('name',sprintf('%d%s',4000 ,' FPS Videos'))
        
        subplot(5,1,1);
        plot([parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.Fo(:)],'.-');
        ylabel('Fo')
        legend('4000','4cut1','4to2cut1','4to8cut2','4to8cut1')
        
        subplot(5,1,2);
        plot([parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.OQ(:)],'.-');
        ylabel('OQ')
        
        subplot(5,1,3);
        plot([parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.SI(:)],'.-');
        ylabel('SI')
        
        subplot(5,1,4);
        plot([parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.RGG(:)],'.-');
        ylabel('RGG')
        
        subplot(5,1,5);
        plot([parray(vid_num).freqN(freqn).rateN(2).cutN(2).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(2).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.HNR(:)],'.-');
        ylabel('HNR')
        
        %         fs(end)=[];
        
    elseif ~isempty(fs)&& fs(end)==2
        %plot the 2000 fps video
        %will have id2 2to4cut1 2to8cut1
        figure('name',sprintf('%d%s',2000 ,' FPS Video'))
        
        subplot(5,1,1);
        plot([parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.Fo(:) ... 
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.Fo(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.Fo(:)],'.-');
        ylabel('Fo')
        legend('2000','2to4','2to8')
        
        subplot(5,1,2);
        plot([parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.OQ(:)...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.OQ(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.OQ(:)],'.-');
        ylabel('OQ')
        
        subplot(5,1,3);
        plot([parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.SI(:)...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.SI(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.SI(:)],'.-');
        ylabel('SI')
        
        subplot(5,1,4);
        plot([parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.RGG(:)...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.RGG(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.RGG(:)],'.-');
        ylabel('RGG')
        
        subplot(5,1,5);
        plot([parray(vid_num).freqN(freqn).rateN(1).cutN(1).par.HNR(:)...
            parray(vid_num).freqN(freqn).rateN(2).cutN(1).par.HNR(:) ...
            parray(vid_num).freqN(freqn).rateN(3).cutN(1).par.HNR(:)],'.-');
        ylabel('HNR')
    end
end
end


